# Path to your oh-my-zsh installation.
ZSH_THEME="steeef"
DISABLE_AUTO_TITLE="true"
HIST_STAMPS="mm/dd/yyyy"


export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/$(whoami)/Bin:/home/$(whoami)/Draft-bin"

#python virtual environment
export WORKON_HOME=$HOME/.virtualenvs
plugins=(git autojump colored-man sudo zsh_reload virtualenvwrapper virtualenv)


# locale
export LANG=en_US.UTF-8
export LC_CTYPE=zh_CN.UTF-8

# ssh keys
export SSH_KEY_PATH="~/.ssh/dsa_id"

# blog server
export POST_DIR=/home/$(whoami)/Projects/fishcried.github.io
export DRAFT_DIR=$POST_DIR

export ZSH=/home/$(whoami)/.oh-my-zsh
source $ZSH/oh-my-zsh.sh
