#!/bin/bash
#
# The MIT License (MIT)
# Copyright (c) 2014 fishcried(tianqing.w@gmail.com)
#

function usage()
{
	echo "$(basename $0) post|draft"
	echo " post  run post blog server,the port is 4000"
	echo " draft run post drafts server, the port is 4001"
}


[ $# -ne 1 ] && usage && exit 1


case $1 in
	*post*)
		if [ "x$POST_DIR" == "x" ];then
			echo "POST_DIR not define."
			exit 2
		fi
		cd $POST_DIR 
		jekyll server --watch -H 0.0.0.0 -P 4000  ;;
	*draft*)
		if [ "x$DRAFT_DIR" == "x" ];then
			echo "DRAFT_DIR not define."
			exit 2
		fi
		cd $DRAFT_DIR 
		jekyll server --watch -D -H 0.0.0.0 -P 4001  ;;
	*)
		usage
		exit 1;;
esac
